### ISSUE TITLE
when copy the QR code the "Copied" tip need to display

### ISSUE THREAD

**Issue by lakshmirvm** [spacescan-io/docs#147]
After clicking "copy to clipboard" in wallet connect ,better to display "copied" tip to easy understand by the user.
![image](https://github.com/spacescan-io/docs/assets/130156384/dc764c2d-c9d9-4fa5-a641-b4863929c349)

**Comment by SathyaSeelanG** [comment]
![Image](https://github.com/spacescan-io/docs/assets/120622131/41d92b8a-5ab7-4096-b223-89e9b2c8de97)

**Comment by lakshmirvm** [comment]
clicking on the" copy to clipboard" didn't copy any link.so couldn't connect the wallet

**Comment by lakshmirvm** [comment]
fixed
